---
version: '3.4'

services:
  confluentcontrolcenter:
    image: confluentinc/cp-enterprise-control-center:${VERSION_CONFLUENT}
    restart: unless-stopped
    hostname: confluentcontrolcenter.${DOMAIN_NAME}
    environment:
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_CONNECT_CLUSTER: 'http://kafkaconnect:8083'
      CONTROL_CENTER_REPLICATION_FACTOR: 3
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    networks:
      default:
        aliases:
          - confluentcontrolcenter.${DOMAIN_NAME}

networks:
  default:
...