---
version: '3.4'

services:
  schemaregistry1:
    image: confluentinc/cp-schema-registry:${VERSION_CONFLUENT}
    restart: unless-stopped
    hostname: schemaregistry1.${DOMAIN_NAME}
    environment:
      SCHEMA_REGISTRY_HOST_NAME: "schemaregistry1.${DOMAIN_NAME}"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: "full_transitive"
      SCHEMA_REGISTRY_MASTER_ELIGIBILITY: "true"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
    networks:
      default:
        aliases:
          - schemaregistry
          - schemaregistry.${DOMAIN_NAME}
          - schemaregistry1.${DOMAIN_NAME}

  schemaregistry2:
    image: confluentinc/cp-schema-registry:${VERSION_CONFLUENT}
    restart: unless-stopped
    hostname: schemaregistry2.${DOMAIN_NAME}
    environment:
      SCHEMA_REGISTRY_HOST_NAME: "schemaregistry2.${DOMAIN_NAME}"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR: 3
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: "full_transitive"
      SCHEMA_REGISTRY_MASTER_ELIGIBILITY: "true"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS: "GET,POST,PUT,OPTIONS"
      SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
    networks:
      default:
        aliases:
          - schemaregistry
          - schemaregistry.${DOMAIN_NAME}
          - schemaregistry2.${DOMAIN_NAME}

  schemaregistryui:
    image: landoop/schema-registry-ui
    restart: unless-stopped
    hostname: schemaregistryui.${DOMAIN_NAME}
    environment:
      SCHEMAREGISTRY_URL: "http://schemaregistry.${DOMAIN_NAME}:8081"
    networks:
      default:
        aliases:
          - schemaregistryui
          - schemaregistryui.${DOMAIN_NAME}

networks:
  default:
...