global:
  scrape_interval: 20s
scrape_configs:
  - job_name: kafka-jmx
    scrape_timeout: 15s
    static_configs:
      - targets:
          - "kafka1prometheusexporter.@DOMAIN_NAME@:9404"
          - "kafka2prometheusexporter.@DOMAIN_NAME@:9404"
          - "kafka3prometheusexporter.@DOMAIN_NAME@:9404"
          - "kafka4prometheusexporter.@DOMAIN_NAME@:9404"
    relabel_configs:
      - source_labels: [__address__]
        regex: (kafka\d)prometheusexporter.@DOMAIN_NAME@:9404
        target_label: node_target
      - source_labels: [__address__]
        regex: (kafka\dprometheusexporter).@DOMAIN_NAME@:9404
        target_label: node_monitor